site_name: 我的文档库
site_description: 基于 MkDocs Material 构建的文档站点
site_url: https://jamesbriand.github.io/llm-self-learning/

nav:
  - 首页: index.md
  - 入门指南:
    - getting-started/index.md
  - 教程:
    - 编写第一篇文档: tutorials/first-document.md
  - 参考文档:
    - Markdown 语法: reference/markdown.md

theme:
  name: material
  language: zh
  palette:
    # 浅色模式
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: 切换到深色模式
    # 深色模式
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: 切换到浅色模式
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - header.autohide
    - content.code.copy

plugins:
  - search:
      lang: zh

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
