site_name: LLM 自学指南
site_description: 大语言模型与AI学习资源汇总
site_url: https://jamesbriand.github.io/llm-self-learning/

nav:
  - 首页: index.md
  - 学习指南: getting-started/index.md
  - 模型基础:
    - 第1节 Transformer基础: 
      - 学习概览: fundamentals/transformer/index.md
      - Attention机制: fundamentals/transformer/attention.md
      - 前馈神经网络: fundamentals/transformer/ffn.md
      - 编码器-解码器架构: fundamentals/transformer/encoder-decoder.md
      - 语言模型架构: fundamentals/transformer/language-models.md
      - Tokenizer技术: fundamentals/transformer/tokenizer.md
    - 第2节 Attention升级:
      - 学习概览: fundamentals/attention-advanced/index.md
      - 多头注意力变体: fundamentals/attention-advanced/mha-variants.md
      - KV Cache技术: fundamentals/attention-advanced/kv-cache.md
      - 归一化技术: fundamentals/attention-advanced/normalization.md
      - 位置编码: fundamentals/attention-advanced/positional-encoding.md
    - 第3节 LLM升级技术:
      - 学习概览: fundamentals/llm-advanced/index.md
      - MOE架构: fundamentals/llm-advanced/moe.md
      - 分布式训练: fundamentals/llm-advanced/distributed.md
    - 第4节 DeepSeek优化技术:
      - 学习概览: fundamentals/deepseek-innovations/index.md
      - MLA核心技术: fundamentals/deepseek-innovations/mla.md
      - DeepSeek MoE创新: fundamentals/deepseek-innovations/deepseek-moe.md
      - MTP多token预测: fundamentals/deepseek-innovations/mtp.md
  - 模型训练:
    - 第8节 强化学习与对齐:
      - 学习概览: training/rlhf-alignment/index.md
      - RLHF核心技术: training/rlhf-alignment/rlhf-core.md
      - DPO与Constitutional AI: training/rlhf-alignment/dpo-constitutional.md
      - 奖励模型训练: training/rlhf-alignment/reward-modeling.md
      - 框架与实现: training/rlhf-alignment/frameworks-implementation.md
  - 大模型应用:
    - 第5节 Context Engineering:
      - 学习概览: applications/context-engineering/index.md
      - 上下文工程实践: applications/context-engineering/practices.md
    - 第6节 RAG与Agent:
      - 学习概览: applications/rag-agent/index.md
      - RAG技术: applications/rag-agent/rag.md
      - AI Agent: applications/rag-agent/agent.md
    - 第7节 CoT与评测:
      - 学习概览: applications/cot-evaluation/index.md
      - 思维链技术: applications/cot-evaluation/cot.md
      - LangChain框架: applications/cot-evaluation/langchain.md
      - 模型评测: applications/cot-evaluation/evaluation.md
  - 面试题库: interview/index.md
  - 代码实现: code-examples/index.md

theme:
  name: material
  language: zh
  static_templates:
    - 404.html
  favicon: assets/images/favicon.png
  include_search_page: false
  search_index_only: true

  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto Slab
    code: Roboto Mono

plugins:
  - search:
      lang:
        - zh
        - en

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - tables
  - toc:
      permalink: true

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
