site_name: LLM 自学指南
site_description: 大语言模型与AI学习资源汇总
site_url: https://jamesbriand.github.io/llm-self-learning/

nav:
  - 首页: index.md
  - 入门指南:
    - getting-started/index.md
  - 教程:
    - 编写第一篇文档: tutorials/first-document.md
  - 参考文档:
    - Markdown 语法: reference/markdown.md

theme:
  name: material
  language: zh
  static_templates:
    - 404.html
  favicon: assets/images/favicon.png
  include_search_page: false
  search_index_only: true

  features:
    - header.autohide
    - navigation.tracking
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - content.code.annotate

  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: cyan
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

  font:
    text: Roboto Slab
    code: Roboto Mono

plugins:
  - search:
      lang:
        - zh
        - en

markdown_extensions:
  - attr_list
  - md_in_html
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: true
